import { CrmField, CrmFieldType } from '../../entities/crm-field.entity';

export const crmFieldsSeeds: Partial<CrmField>[] = [
  // Contact Information Fields
  {
    name: 'contact_source',
    label: 'Contact Source',
    fieldType: CrmFieldType.SELECT,
    description: 'How the lead was acquired',
    isRequired: true,
    options: ['Website', 'Social Media', 'Referral', 'Cold Call', 'Email Campaign', 'Event', 'Partner'],
    sortOrder: 1,
  },
  {
    name: 'lead_quality',
    label: 'Lead Quality',
    fieldType: CrmFieldType.SELECT,
    description: 'Quality assessment of the lead',
    isRequired: false,
    options: ['Hot', 'Warm', 'Cold', 'Qualified', 'Unqualified'],
    sortOrder: 2,
  },
  {
    name: 'budget_range',
    label: 'Budget Range',
    fieldType: CrmFieldType.SELECT,
    description: 'Estimated budget range',
    isRequired: false,
    options: ['< $1,000', '$1,000 - $5,000', '$5,000 - $10,000', '$10,000 - $25,000', '$25,000+'],
    sortOrder: 3,
  },
  {
    name: 'decision_timeline',
    label: 'Decision Timeline',
    fieldType: CrmFieldType.SELECT,
    description: 'Expected decision timeline',
    isRequired: false,
    options: ['Immediate', 'Within 1 month', '1-3 months', '3-6 months', '6+ months'],
    sortOrder: 4,
  },
  {
    name: 'pain_points',
    label: 'Pain Points',
    fieldType: CrmFieldType.TEXTAREA,
    description: 'Key challenges the lead is facing',
    isRequired: false,
    maxLength: 1000,
    sortOrder: 5,
  },
  {
    name: 'decision_maker',
    label: 'Decision Maker',
    fieldType: CrmFieldType.BOOLEAN,
    description: 'Is this contact the decision maker?',
    isRequired: false,
    sortOrder: 6,
  },
  {
    name: 'competitor_info',
    label: 'Competitor Information',
    fieldType: CrmFieldType.TEXTAREA,
    description: 'Information about competitors they are considering',
    isRequired: false,
    maxLength: 500,
    sortOrder: 7,
  },
  {
    name: 'preferred_contact_method',
    label: 'Preferred Contact Method',
    fieldType: CrmFieldType.SELECT,
    description: 'How they prefer to be contacted',
    isRequired: false,
    options: ['Email', 'Phone', 'WhatsApp', 'In-person Meeting', 'Video Call'],
    sortOrder: 8,
  },
  {
    name: 'team_size',
    label: 'Team Size',
    fieldType: CrmFieldType.NUMBER,
    description: 'Size of their team/organization',
    isRequired: false,
    sortOrder: 9,
  },
  {
    name: 'annual_revenue',
    label: 'Annual Revenue',
    fieldType: CrmFieldType.SELECT,
    description: 'Company annual revenue range',
    isRequired: false,
    options: ['< $100K', '$100K - $500K', '$500K - $1M', '$1M - $5M', '$5M - $10M', '$10M+'],
    sortOrder: 10,
  },
];