version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: crm_db
    environment:
      POSTGRES_USER: crm
      POSTGRES_PASSWORD: crm
      POSTGRES_DB: crm
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U crm -d crm']
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  db_data:
