name: Render ER Diagram

on:
  push:
    branches:
      - main
    paths:
      - 'er/diagram.mmd'
      - '.github/workflows/er-diagram.yml'

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Render PNG via Kroki
        run: |
          curl -fSL -X POST \
            -H "Content-Type: text/plain" \
            --data-binary @er/diagram.mmd \
            https://kroki.io/mermaid/png \
            -o er/diagram.png

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Convert PNG to JPG
        run: convert er/diagram.png -background white -alpha remove -alpha off -quality 92 er/diagram.jpg

      - name: Commit rendered diagrams
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "build(er): render ER diagram PNG/JPG via Kroki"
          file_pattern: |
            er/diagram.png
            er/diagram.jpg